language: crystal
script:
  - shards install
  - crystal spec
  - crystal docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: docs